name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Create .env file
        uses: ozaytsev86/create-env-file@v1
        with:
          ENV_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          ENV_TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
      - name: Send to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          port: 22
          source: .
          target: ~/nasakh-api/
        
